### ISSUE TITLE
Database may be already in use: null 

### ISSUE THREAD

**Issue by edoreld** [LAntoine/LAMSADE-tools#36]
Happens from time to time, when launching the GUI or when using the conference menu a few times. 

<details> 
  <summary>Full Error Log </summary>
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:187)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:167)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2468)
	at org.h2.engine.Database.open(Database.java:695)
	at org.h2.engine.Database.openDatabase(Database.java:273)
	at org.h2.engine.Database.<init>(Database.java:267)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:115)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:99)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:188)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:351)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:383)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:225)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:197)
	at com.github.lamsadetools.conferences.database.ConnectionDataBase.getConnection(ConnectionDataBase.java:34)
	at com.github.lamsadetools.conferences.database.ConferenceDatabase.returnAllConferencesFromDatabase(ConferenceDatabase.java:292)
	at com.github.lamsadetools.graphical_interface.Tester.fillConferenceTable(Tester.java:59)
	at com.github.lamsadetools.graphical_interface.Tester.main(Tester.java:120)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/edoreld/conferences.mv.db [1.4.193/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:348)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2923)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	... 23 more
</details>

My first thought is, there must be a place in the code where the database connection is left open after closing the program.

**Comment by edoreld** [comment]
Reopen if error encountered again.
