### ISSUE TITLE
Graphical Interface not launching with error

### ISSUE THREAD

**Issue by edoreld** [LAntoine/LAMSADE-tools#55]
How to reproduce:
Go to and launch Tester.class in the graphical interface package.

Error:
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Invalid value "7" for parameter "columnIndex" [90008-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:228)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3191)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3219)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:292)
	at com.github.lantoine.lamsadetools.conferences.database.ConferenceDatabase.returnAllConferencesFromDatabase(ConferenceDatabase.java:238)
	at com.github.lantoine.lamsadetools.graphical_interface.Tester.fillConferenceTable(Tester.java:83)
	at com.github.lantoine.lamsadetools.graphical_interface.Tester.main(Tester.java:254)

**Comment by LAntoine** [comment]
As I told you on Slack we changed the structure of one table, so you need to delete the database manually or execute execute the ClearDatabase method from ConferenceDatabase.
Maybe you should catch this error and execute the ClearDatabase in your graphical interface class.

**Comment by edoreld** [comment]
Issue is solved.
